-- Databricks notebook source
CREATE TABLE IF NOT EXISTS llm.pdf_text ( id BIGINT GENERATED BY DEFAULT AS IDENTITY, text STRING ) tblproperties (delta.enableChangeDataFeed = true);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS llm.docs_track (file_name STRING) tblproperties (delta.enableChangeDataFeed = true);
